name: cardano-config
version: 20240702
description: Configuration files for the Cardano node by Input Output Global
installSteps:
  - docker:
      containerName: cardano-configs
      image: ghcr.io/blinklabs-io/cardano-configs:20240702-1
      pullOnly: true
outputs:
  - name: base
    description: Path to the Cardano Node configuration files
    value: '{{ .Paths.ContextDir }}/config'
postInstallScript: |
  set -e
  mkdir -p {{ .Paths.ContextDir }}/config
  docker create --name {{ .Package.Name }}-{{ .Package.ShortName }} ghcr.io/blinklabs-io/cardano-configs:20240702-1 bash
  docker cp {{ .Package.Name }}-{{ .Package.ShortName }}:/config/{{ .Context.Network }}/ {{ .Paths.ContextDir }}/config/
  docker rm {{ .Package.Name }}-{{ .Package.ShortName }}
tags:
  - docker
  - linux
  - darwin
  - amd64
  - arm64
