name: package-validate

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - run: make
      - run: ./cardano-up validate -D
